<a href="https://colab.research.google.com/github/a-forty-two/GCPProMLE4Sep23/blob/main/SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow import keras
import tensorflow

In [2]:
alldata = keras.datasets.imdb
dir(alldata)


['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'get_word_index',
 'load_data']

In [3]:
data = alldata.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [4]:
len(data), len(data[0])

(2, 2)

In [8]:
len(data[1][1])

25000

In [ ]:
#print(xtrain[142])

In [9]:
HP_vocab_size = 10000
HP_epochs = 50
HP_batch_size = 32
HP_maxlen = 256
HP_initial_LR = 0.001
# when learning is complete, lr = 0!
# 0 = 1e-3 + decay_rate * 50


In [10]:
opt = keras.optimizers.Adam(
    learning_rate=HP_initial_LR)

In [11]:
(xtrain, ytrain), (xtest, ytest) = keras.datasets.imdb.load_data(
    num_words = HP_vocab_size
)

In [12]:
ytrain[0], ytrain[789]

(1, 0)

In [13]:
print(xtrain[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [14]:
vocab = alldata.get_word_index()

1641221/1641221 [==============================] - 0s 0us/step


In [15]:
rev_vocab = { v:k for k,v in vocab.items()}

In [16]:
def decoder(sentence):
  words= [ rev_vocab[word]  for word in sentence]
  full_sentence = " ".join(words)
  return full_sentence

In [17]:
decoder(xtrain[90])

"the this enough premiere and better executed ability br and with his her and movie it stick politics i i was one is excellent cut this and only natural with lot br of how truly full this of want f br and pop and off that however of here br realistically and me will her points violent this and of 1 for from me in and of guy to simple or and this seen money pleasures sees hours is exciting and guy to sets shockingly and ability his is displays really me of truly and br and and with is quite touches in of i've been stick politics i i of she's it for of house geniuses for its great does it of complicated down roth cute dies are and are arrived really disaster and rented movie trite of thought group fun to big was can about previous are and to sentiment historical those are for top and with is word bath this of neil whether and to audience and with table and who private and yes br complicated sirk was let musicals was two that with and happen can't ok in out imagination i i they by my comp

In [ ]:
decoder(xtrain[2090])

"the as on it has is time nowhere slack aspects idea like it jon in gadget is during doing and fascinated ways sets in targeted and and that mean floors rent psyche this of white almost to would end movie has movie much movie of guy grew was two and beau story one will is still moves not cartoon of complete heroes day on wrong from away against glorious about floors rent end few him this us nice not bad best also in can about used struggling of their it around straight in why of there's newspaper even focused is got to african close and there of forced michael almost all it of idea are of ways to other of did cut but floors rent and and there is again spend something movie of list work say like cat of mack 80s to thing two is found real gadget theaters as come it hear she unfortunately of you to burt in why it prove union floors rent thing maybe about ways i'm think and faster gimmicks would thing people last is forced gadget attempt people more it is makes hatred jim is timeless to hi

In [18]:
# 0 <PAD>
# 1 <START>
# 2 <UNKNOWN>
# 3 <UNUSED>
rev_new_vocab = { }

In [ ]:
#rev_vocab[1], rev_vocab[0]

In [19]:
fixed_dict = { k:v+3 for k,v in vocab.items()}
rev_fixed_vocab = { v:k for k,v in fixed_dict.items() }

In [20]:
rev_fixed_vocab[41]

'her'

In [21]:
rev_fixed_vocab[0] = "<PAD>"
rev_fixed_vocab[1] = "<START>"
rev_fixed_vocab[2] = "<UNK>"
rev_fixed_vocab[3] = "<UNUSED>"

In [22]:
def decoder(sentence):
  words= [ rev_fixed_vocab[word]  for word in sentence]
  full_sentence = " ".join(words)
  return full_sentence

In [31]:
decoder(xtrain[5015])

"<START> this is a fantastic series first and foremost it is very well done and very interesting as a huge wwii buff i had learned a lot before seeing this series one of the best things this has going for it is all the interviews with past individuals back when the war was relatively fresh in their minds <UNK> speaking that is it is nothing against the men that you see getting interviewed in the programs of today it is just that most of these men weren't really involved in the upper <UNK> of what was happening then one of the best parts is the <UNK> by sir laurence oliver i would recommend this to anyone that wants to learn about wwii but really think only the die <UNK> such as myself will want to buy this or watch it more than once my only real complaint about this entire series is that some of the facts aren't quite as accurate as we now know especially with the information about soviet union is exaggerated or just plain inaccurate in places that information is now different we now k

In [32]:
ytrain[5015]

1

In [33]:
for i in range(10):
  print(len(xtrain[i]))

218
189
141
550
147
43
123
562
233
130


In [34]:
xtrain_padded = keras.preprocessing.sequence.pad_sequences(
    xtrain, maxlen = HP_maxlen,
    truncating = 'post', padding = 'post'
)

In [35]:
xtrain_padded[3]

array([   1,    4,    2,    2,   33, 2804,    4, 2040,  432,  111,  153,
        103,    4, 1494,   13,   70,  131,   67,   11,   61,    2,  744,
         35, 3715,  761,   61, 5766,  452, 9214,    4,  985,    7,    2,
         59,  166,    4,  105,  216, 1239,   41, 1797,    9,   15,    7,
         35,  744, 2413,   31,    8,    4,  687,   23,    4,    2, 7339,
          6, 3693,   42,   38,   39,  121,   59,  456,   10,   10,    7,
        265,   12,  575,  111,  153,  159,   59,   16, 1447,   21,   25,
        586,  482,   39,    4,   96,   59,  716,   12,    4,  172,   65,
          9,  579,   11, 6004,    4, 1615,    5,    2,    7, 5168,   17,
         13, 7064,   12,   19,    6,  464,   31,  314,   11,    2,    6,
        719,  605,   11,    8,  202,   27,  310,    4, 3772, 3501,    8,
       2722,   58,   10,   10,  537, 2116,  180,   40,   14,  413,  173,
          7,  263,  112,   37,  152,  377,    4,  537,  263,  846,  579,
        178,   54,   75,   71,  476,   36,  413,  2

In [36]:
xtrain_padded[5]

array([   1,  778,  128,   74,   12,  630,  163,   15,    4, 1766, 7982,
       1051,    2,   32,   85,  156,   45,   40,  148,  139,  121,  664,
        665,   10,   10, 1361,  173,    4,  749,    2,   16, 3804,    8,
          4,  226,   65,   12,   43,  127,   24,    2,   10,   10,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [37]:
for i in range(10):
  print(len(xtrain_padded[i]), end=" ")

256 256 256 256 256 256 256 256 256 256 

In [ ]:
import tensorflow as tf
from keras.layers import Embedding, GlobalAvgPool1D
from keras.layers import Dense
m = keras.Sequential([
        Embedding(10000, 32),
        GlobalAvgPool1D(),
        Dense(256),
        Dense(512),
        Dense(1)
])

In [ ]:
m.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 32)          320000    
                                                                 
 global_average_pooling1d_3   (None, 32)               0         
 (GlobalAveragePooling1D)                                        
                                                                 
 dense_6 (Dense)             (None, 256)               8448      
                                                                 
 dense_7 (Dense)             (None, 512)               131584    
                                                                 
 dense_8 (Dense)             (None, 1)                 513       
                                                                 
Total params: 460,545
Trainable params: 460,545
Non-trainable params: 0
________________________________________________

In [ ]:
m.compile(loss = 'binary_crossentropy',
          optimizer='adam')

In [ ]:
m.fit(xtrain_padded, ytrain, epochs=20)

Epoch 1/20
782/782 [==============================] - 12s 13ms/step - loss: 0.3889
Epoch 2/20
782/782 [==============================] - 10s 13ms/step - loss: 0.2218
Epoch 3/20
782/782 [==============================] - 10s 13ms/step - loss: 0.1805
Epoch 4/20
782/782 [==============================] - 10s 13ms/step - loss: 0.1488
Epoch 5/20
782/782 [==============================] - 10s 13ms/step - loss: 0.1223
Epoch 6/20
782/782 [==============================] - 11s 14ms/step - loss: 0.0952
Epoch 7/20
782/782 [==============================] - 10s 13ms/step - loss: 0.0755
Epoch 8/20
782/782 [==============================] - 10s 13ms/step - loss: 0.0684
Epoch 9/20
782/782 [==============================] - 12s 15ms/step - loss: 0.0508
Epoch 10/20
782/782 [==============================] - 11s 14ms/step - loss: 0.0420
Epoch 11/20
782/782 [==============================] - 10s 13ms/step - loss: 0.0375
Epoch 12/20
782/782 [==============================] - 10s 13ms/step - loss: 0.0265
E

In [ ]:
xtest_padded = keras.preprocessing.sequence.pad_sequences(
    xtest, padding='post', truncating='post'
)
p = m.predict(xtest_padded)

In [ ]:
p[:5]
mapping_logic = lambda x: 1 if x>0.75 else 0
predictions = [mapping_logic(pred) for pred in p]

In [ ]:
ytest[:5]

array([0, 1, 1, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(predictions, ytest)

0.79148

In [ ]:
m.save('blah.h5')

In [ ]:
import tensorflow as tf
tf.__version__

'2.8.2'